# Generated by Django 2.0.4 on 2018-04-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impactquote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='movie',
            field=models.CharField(default='text', max_length=100),
        ),
    ]
