# Generated by Django 2.0.4 on 2018-04-14 09:24

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('impactquote', '0002_quote_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Widget',
        ),
        migrations.AddField(
            model_name='quote',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
